import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sfProText = localFont({
  src: "../assets/fonts/SF-Pro-Text-Regular.otf",
  variable: "--font-sf-pro-text",
  display: "swap",
});

const sfProDisplay = localFont({
  src: "../assets/fonts/SF-Pro-Display-Regular.otf",
  variable: "--font-sf-pro-display",
  display: "swap",
});

const sfMono = localFont({
  src: "../assets/fonts/SF-Mono-Regular.otf",
  variable: "--font-sf-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sfProText.variable} ${sfProDisplay.variable} ${sfMono.variable} dark h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
