#!/usr/bin/env bun
import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import {
  DEFAULT_API_BASE_URL,
  DEFAULT_API_CORS_ORIGINS,
  DEFAULT_JWT_EXPIRES_IN,
  DEFAULT_SHADOWTLS_HANDSHAKE_PORT,
  DEFAULT_SHADOWTLS_HANDSHAKE_SERVER,
  DEFAULT_SING_BOX_COMMAND,
  DEFAULT_SING_BOX_CONFIG_PATH,
  DEFAULT_SING_BOX_SYSTEMD_UNIT,
  DEFAULT_SYSTEMCTL_COMMAND,
  DEFAULT_SYSTEMD_SCOPE,
  type SystemdScope,
} from "@box-winder/config";
import { DEFAULT_SING_BOX_PORT_BASE } from "@box-winder/core";
import { Command, InvalidArgumentError } from "commander";

type RenderSystemdEnvOptions = {
  allowMissing?: boolean;
  env?: NodeJS.ProcessEnv;
  scope?: SystemdScope;
};

type EnvSpec = {
  key: string;
  required?: boolean;
  value: (input: {
    env: NodeJS.ProcessEnv;
    scope: SystemdScope;
  }) => string | undefined;
};

const ENV_SPECS: EnvSpec[] = [
  envSpec("NODE_ENV", "production"),
  envSpec("HOST", "0.0.0.0"),
  envSpec("PORT", "12000"),
  envSpec("JWT_EXPIRES_IN", DEFAULT_JWT_EXPIRES_IN),
  requiredEnvSpec("JWT_SECRET"),
  envSpec("API_CORS_ORIGINS", DEFAULT_API_CORS_ORIGINS.join(",")),
  requiredEnvSpec("DATABASE_URL"),
  envSpec("SING_BOX_PORT_BASE", String(DEFAULT_SING_BOX_PORT_BASE)),
  scopeEnvSpec(),
  envSpec("BOX_WINDER_SING_BOX_CONFIG_PATH", ({ scope }) =>
    scope === "user"
      ? join(defaultXdgStateHome(), "box-winder", "sing-box", "config.json")
      : DEFAULT_SING_BOX_CONFIG_PATH,
  ),
  envSpec("BOX_WINDER_SING_BOX_SYSTEMD_UNIT", DEFAULT_SING_BOX_SYSTEMD_UNIT),
  optionalEnvSpec("SING_BOX_MASTER_SECRET"),
  envSpec("SING_BOX_COMMAND", DEFAULT_SING_BOX_COMMAND),
  envSpec("SYSTEMCTL_COMMAND", DEFAULT_SYSTEMCTL_COMMAND),
  requiredEnvSpec("DOMAIN_NAME"),
  requiredEnvSpec("ACME_EMAIL"),
  requiredEnvSpec("CLOUDFLARE_API_TOKEN"),
  envSpec("SHADOWTLS_HANDSHAKE_SERVER", DEFAULT_SHADOWTLS_HANDSHAKE_SERVER),
  envSpec("SHADOWTLS_HANDSHAKE_PORT", String(DEFAULT_SHADOWTLS_HANDSHAKE_PORT)),
  envSpec("NODE_LOCATION", "JP"),
  envSpec("SUBSCRIPTION_TEMPLATE_DIR", "assets/templates/subscriptions"),
  envSpec("API_BASE_URL", DEFAULT_API_BASE_URL),
];

export function renderSystemdEnvFile(
  options: RenderSystemdEnvOptions = {},
): string {
  const env = options.env ?? process.env;
  const scope = options.scope ?? readScope(env.BOX_WINDER_SYSTEMD_SCOPE);
  const missing: string[] = [];
  const lines = [
    "# Generated by box-winder. Edit the active environment, then render again.",
  ];

  for (const spec of ENV_SPECS) {
    const value = spec.value({ env, scope });

    if (spec.required && !value?.trim()) {
      missing.push(spec.key);
      continue;
    }

    if (value === undefined) {
      continue;
    }

    lines.push(`${spec.key}=${quoteSystemdEnvValue(value)}`);
  }

  if (missing.length > 0 && !options.allowMissing) {
    throw new Error(
      `Missing required environment variables: ${missing.join(", ")}`,
    );
  }

  return `${lines.join("\n")}\n`;
}

export function defaultSystemdEnvPath(scope: SystemdScope): string {
  if (scope === "user") {
    return join(defaultXdgConfigHome(), "box-winder", "box-winder.env");
  }

  return "/etc/box-winder/box-winder.env";
}

export function quoteSystemdEnvValue(value: string): string {
  if (/[\r\n]/.test(value)) {
    throw new Error("systemd EnvironmentFile values must be single-line");
  }

  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

async function main(): Promise<void> {
  const program = new Command()
    .name("systemd:env")
    .description(
      "Render a systemd EnvironmentFile from the current environment",
    )
    .option("--scope <scope>", "systemd scope: user or system", parseScope)
    .option("--out <path>", "output EnvironmentFile path")
    .option("--print", "print the rendered env file to stdout")
    .option(
      "--allow-missing",
      "render placeholder-free output even if required variables are missing",
    );

  program.parse();

  const options = program.opts<{
    allowMissing?: boolean;
    out?: string;
    print?: boolean;
    scope?: SystemdScope;
  }>();
  const scope =
    options.scope ?? readScope(process.env.BOX_WINDER_SYSTEMD_SCOPE);
  const output = renderSystemdEnvFile({
    allowMissing: options.allowMissing,
    scope,
  });

  if (options.print) {
    process.stdout.write(output);
    return;
  }

  const outPath = options.out ?? defaultSystemdEnvPath(scope);
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, output, { mode: 0o600 });
  console.log(`Rendered systemd env file: ${outPath}`);
}

function envSpec(
  key: string,
  fallback:
    | string
    | ((input: { env: NodeJS.ProcessEnv; scope: SystemdScope }) => string),
): EnvSpec {
  return {
    key,
    value: (input) => input.env[key] ?? valueFromFallback(fallback, input),
  };
}

function optionalEnvSpec(key: string): EnvSpec {
  return {
    key,
    value: ({ env }) => env[key],
  };
}

function requiredEnvSpec(key: string): EnvSpec {
  return {
    key,
    required: true,
    value: ({ env }) => env[key],
  };
}

function scopeEnvSpec(): EnvSpec {
  return {
    key: "BOX_WINDER_SYSTEMD_SCOPE",
    value: ({ scope }) => scope,
  };
}

function valueFromFallback(
  fallback:
    | string
    | ((input: { env: NodeJS.ProcessEnv; scope: SystemdScope }) => string),
  input: { env: NodeJS.ProcessEnv; scope: SystemdScope },
): string {
  return typeof fallback === "function" ? fallback(input) : fallback;
}

function defaultXdgConfigHome(): string {
  return process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config");
}

function defaultXdgStateHome(): string {
  return process.env.XDG_STATE_HOME ?? join(homedir(), ".local", "state");
}

function readScope(value: string | undefined): SystemdScope {
  if (!value) {
    return DEFAULT_SYSTEMD_SCOPE;
  }

  return parseScope(value);
}

function parseScope(value: string): SystemdScope {
  if (value === "system" || value === "user") {
    return value;
  }

  throw new InvalidArgumentError('scope must be "system" or "user"');
}

if (import.meta.main) {
  await main();
}
